-- AlterTable
ALTER TABLE `product` ADD COLUMN `avgRating` SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN `totalComments` SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN `totalRating` SMALLINT NOT NULL DEFAULT 0;
